
services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
#    volumes:
#      - ./fastapi:/app
#    command: >
#      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  python:
    build:
      context: ./python
